//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.239
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armandorv.EasytravelWsClient.TravelsWs {
    
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://armandorv.com/easytravel/travelsws/exception")]
    public partial class TravelsWsException : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://armandorv.com/easytravel/travelsws")]
    public partial class user : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string lastnameField;
        
        private string mailField;
        
        private string nameField;
        
        private string passwordField;
        
        private travel[] travelsField;
        
        private string usernameField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
                this.RaisePropertyChanged("lastname");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                this.mailField = value;
                this.RaisePropertyChanged("mail");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("travels", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public travel[] travels {
            get {
                return this.travelsField;
            }
            set {
                this.travelsField = value;
                this.RaisePropertyChanged("travels");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://armandorv.com/easytravel/travelsws")]
    public partial class travel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private destiny[] destiniesField;
        
        private string nameField;
        
        private string summaryField;
        
        private user userField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("destinies", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public destiny[] destinies {
            get {
                return this.destiniesField;
            }
            set {
                this.destiniesField = value;
                this.RaisePropertyChanged("destinies");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string summary {
            get {
                return this.summaryField;
            }
            set {
                this.summaryField = value;
                this.RaisePropertyChanged("summary");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public user user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://armandorv.com/easytravel/travelsws")]
    public partial class destiny : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string addressField;
        
        private System.DateTime estimatedDateField;
        
        private bool estimatedDateFieldSpecified;
        
        private flightBooking[] flightsField;
        
        private hotelBooking[] hotelsField;
        
        private float lattitudeField;
        
        private bool lattitudeFieldSpecified;
        
        private float longitudeField;
        
        private bool longitudeFieldSpecified;
        
        private string nameField;
        
        private destiny nextField;
        
        private destiny previousField;
        
        private string timeZoneField;
        
        private travel travelField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime estimatedDate {
            get {
                return this.estimatedDateField;
            }
            set {
                this.estimatedDateField = value;
                this.RaisePropertyChanged("estimatedDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estimatedDateSpecified {
            get {
                return this.estimatedDateFieldSpecified;
            }
            set {
                this.estimatedDateFieldSpecified = value;
                this.RaisePropertyChanged("estimatedDateSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("flights", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public flightBooking[] flights {
            get {
                return this.flightsField;
            }
            set {
                this.flightsField = value;
                this.RaisePropertyChanged("flights");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("hotels", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public hotelBooking[] hotels {
            get {
                return this.hotelsField;
            }
            set {
                this.hotelsField = value;
                this.RaisePropertyChanged("hotels");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public float lattitude {
            get {
                return this.lattitudeField;
            }
            set {
                this.lattitudeField = value;
                this.RaisePropertyChanged("lattitude");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lattitudeSpecified {
            get {
                return this.lattitudeFieldSpecified;
            }
            set {
                this.lattitudeFieldSpecified = value;
                this.RaisePropertyChanged("lattitudeSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public float longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("longitude");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool longitudeSpecified {
            get {
                return this.longitudeFieldSpecified;
            }
            set {
                this.longitudeFieldSpecified = value;
                this.RaisePropertyChanged("longitudeSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public destiny next {
            get {
                return this.nextField;
            }
            set {
                this.nextField = value;
                this.RaisePropertyChanged("next");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public destiny previous {
            get {
                return this.previousField;
            }
            set {
                this.previousField = value;
                this.RaisePropertyChanged("previous");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string timeZone {
            get {
                return this.timeZoneField;
            }
            set {
                this.timeZoneField = value;
                this.RaisePropertyChanged("timeZone");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public travel travel {
            get {
                return this.travelField;
            }
            set {
                this.travelField = value;
                this.RaisePropertyChanged("travel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://armandorv.com/easytravel/travelsws")]
    public partial class flightBooking : object, System.ComponentModel.INotifyPropertyChanged {
        
        private destiny destinyField;
        
        private flightInfo flightInfoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public destiny destiny {
            get {
                return this.destinyField;
            }
            set {
                this.destinyField = value;
                this.RaisePropertyChanged("destiny");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public flightInfo flightInfo {
            get {
                return this.flightInfoField;
            }
            set {
                this.flightInfoField = value;
                this.RaisePropertyChanged("flightInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://armandorv.com/easytravel/travelsws")]
    public partial class flightInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime arrivalTimeField;
        
        private bool arrivalTimeFieldSpecified;
        
        private System.DateTime departureTimeField;
        
        private bool departureTimeFieldSpecified;
        
        private string destinationAirportICAOField;
        
        private string destinationAirportNameField;
        
        private string destinationCityField;
        
        private string flightIdField;
        
        private string originAirportICAOField;
        
        private string originAirportNameField;
        
        private string originCityField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime arrivalTime {
            get {
                return this.arrivalTimeField;
            }
            set {
                this.arrivalTimeField = value;
                this.RaisePropertyChanged("arrivalTime");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool arrivalTimeSpecified {
            get {
                return this.arrivalTimeFieldSpecified;
            }
            set {
                this.arrivalTimeFieldSpecified = value;
                this.RaisePropertyChanged("arrivalTimeSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime departureTime {
            get {
                return this.departureTimeField;
            }
            set {
                this.departureTimeField = value;
                this.RaisePropertyChanged("departureTime");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool departureTimeSpecified {
            get {
                return this.departureTimeFieldSpecified;
            }
            set {
                this.departureTimeFieldSpecified = value;
                this.RaisePropertyChanged("departureTimeSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string destinationAirportICAO {
            get {
                return this.destinationAirportICAOField;
            }
            set {
                this.destinationAirportICAOField = value;
                this.RaisePropertyChanged("destinationAirportICAO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string destinationAirportName {
            get {
                return this.destinationAirportNameField;
            }
            set {
                this.destinationAirportNameField = value;
                this.RaisePropertyChanged("destinationAirportName");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string destinationCity {
            get {
                return this.destinationCityField;
            }
            set {
                this.destinationCityField = value;
                this.RaisePropertyChanged("destinationCity");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string flightId {
            get {
                return this.flightIdField;
            }
            set {
                this.flightIdField = value;
                this.RaisePropertyChanged("flightId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string originAirportICAO {
            get {
                return this.originAirportICAOField;
            }
            set {
                this.originAirportICAOField = value;
                this.RaisePropertyChanged("originAirportICAO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string originAirportName {
            get {
                return this.originAirportNameField;
            }
            set {
                this.originAirportNameField = value;
                this.RaisePropertyChanged("originAirportName");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string originCity {
            get {
                return this.originCityField;
            }
            set {
                this.originCityField = value;
                this.RaisePropertyChanged("originCity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://armandorv.com/easytravel/travelsws")]
    public partial class hotelBooking : object, System.ComponentModel.INotifyPropertyChanged {
        
        private destiny destinyField;
        
        private hotelInfo hotelInfoField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private int personsField;
        
        private bool personsFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public destiny destiny {
            get {
                return this.destinyField;
            }
            set {
                this.destinyField = value;
                this.RaisePropertyChanged("destiny");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public hotelInfo hotelInfo {
            get {
                return this.hotelInfoField;
            }
            set {
                this.hotelInfoField = value;
                this.RaisePropertyChanged("hotelInfo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int persons {
            get {
                return this.personsField;
            }
            set {
                this.personsField = value;
                this.RaisePropertyChanged("persons");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool personsSpecified {
            get {
                return this.personsFieldSpecified;
            }
            set {
                this.personsFieldSpecified = value;
                this.RaisePropertyChanged("personsSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://armandorv.com/easytravel/travelsws")]
    public partial class hotelInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cityField;
        
        private float highRateField;
        
        private bool highRateFieldSpecified;
        
        private long hotelIdField;
        
        private bool hotelIdFieldSpecified;
        
        private float hotelRatingField;
        
        private bool hotelRatingFieldSpecified;
        
        private string locationDescriptionField;
        
        private float lowRateField;
        
        private bool lowRateFieldSpecified;
        
        private string nameField;
        
        private string phoneNumberField;
        
        private string postalCodeField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public float highRate {
            get {
                return this.highRateField;
            }
            set {
                this.highRateField = value;
                this.RaisePropertyChanged("highRate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool highRateSpecified {
            get {
                return this.highRateFieldSpecified;
            }
            set {
                this.highRateFieldSpecified = value;
                this.RaisePropertyChanged("highRateSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long hotelId {
            get {
                return this.hotelIdField;
            }
            set {
                this.hotelIdField = value;
                this.RaisePropertyChanged("hotelId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hotelIdSpecified {
            get {
                return this.hotelIdFieldSpecified;
            }
            set {
                this.hotelIdFieldSpecified = value;
                this.RaisePropertyChanged("hotelIdSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public float hotelRating {
            get {
                return this.hotelRatingField;
            }
            set {
                this.hotelRatingField = value;
                this.RaisePropertyChanged("hotelRating");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hotelRatingSpecified {
            get {
                return this.hotelRatingFieldSpecified;
            }
            set {
                this.hotelRatingFieldSpecified = value;
                this.RaisePropertyChanged("hotelRatingSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string locationDescription {
            get {
                return this.locationDescriptionField;
            }
            set {
                this.locationDescriptionField = value;
                this.RaisePropertyChanged("locationDescription");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public float lowRate {
            get {
                return this.lowRateField;
            }
            set {
                this.lowRateField = value;
                this.RaisePropertyChanged("lowRate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lowRateSpecified {
            get {
                return this.lowRateFieldSpecified;
            }
            set {
                this.lowRateFieldSpecified = value;
                this.RaisePropertyChanged("lowRateSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("phoneNumber");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("postalCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://armandorv.com/easytravel/travelsws", ConfigurationName="TravelsWs.travelsWebService")]
    internal interface travelsWebService {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Armandorv.EasytravelWsClient.TravelsWs.TravelsWsException), Action="", Name="TravelsWsException", Namespace="http://armandorv.com/easytravel/travelsws/exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Armandorv.EasytravelWsClient.TravelsWs.mostVistedDestinationResponse mostVistedDestination(Armandorv.EasytravelWsClient.TravelsWs.mostVistedDestination request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Armandorv.EasytravelWsClient.TravelsWs.TravelsWsException), Action="", Name="TravelsWsException", Namespace="http://armandorv.com/easytravel/travelsws/exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Armandorv.EasytravelWsClient.TravelsWs.getTravelsResponse getTravels(Armandorv.EasytravelWsClient.TravelsWs.getTravels request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Armandorv.EasytravelWsClient.TravelsWs.TravelsWsException), Action="", Name="TravelsWsException", Namespace="http://armandorv.com/easytravel/travelsws/exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Armandorv.EasytravelWsClient.TravelsWs.mostVistedDestinationsResponse mostVistedDestinations(Armandorv.EasytravelWsClient.TravelsWs.mostVistedDestinations request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Armandorv.EasytravelWsClient.TravelsWs.TravelsWsException), Action="", Name="TravelsWsException", Namespace="http://armandorv.com/easytravel/travelsws/exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Armandorv.EasytravelWsClient.TravelsWs.isVisitedResponse isVisited(Armandorv.EasytravelWsClient.TravelsWs.isVisited request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Armandorv.EasytravelWsClient.TravelsWs.TravelsWsException), Action="", Name="TravelsWsException", Namespace="http://armandorv.com/easytravel/travelsws/exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Armandorv.EasytravelWsClient.TravelsWs.numberTravelsByDestinationResponse numberTravelsByDestination(Armandorv.EasytravelWsClient.TravelsWs.numberTravelsByDestination request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mostVistedDestination", WrapperNamespace="http://armandorv.com/easytravel/travelsws", IsWrapped=true)]
    internal partial class mostVistedDestination {
        
        public mostVistedDestination() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mostVistedDestinationResponse", WrapperNamespace="http://armandorv.com/easytravel/travelsws", IsWrapped=true)]
    internal partial class mostVistedDestinationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://armandorv.com/easytravel/travelsws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Armandorv.EasytravelWsClient.TravelsWs.destiny @return;
        
        public mostVistedDestinationResponse() {
        }
        
        public mostVistedDestinationResponse(Armandorv.EasytravelWsClient.TravelsWs.destiny @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTravels", WrapperNamespace="http://armandorv.com/easytravel/travelsws", IsWrapped=true)]
    internal partial class getTravels {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://armandorv.com/easytravel/travelsws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string term;
        
        public getTravels() {
        }
        
        public getTravels(string term) {
            this.term = term;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTravelsResponse", WrapperNamespace="http://armandorv.com/easytravel/travelsws", IsWrapped=true)]
    internal partial class getTravelsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://armandorv.com/easytravel/travelsws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public travel[] @return;
        
        public getTravelsResponse() {
        }
        
        public getTravelsResponse(travel[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mostVistedDestinations", WrapperNamespace="http://armandorv.com/easytravel/travelsws", IsWrapped=true)]
    internal partial class mostVistedDestinations {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://armandorv.com/easytravel/travelsws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public mostVistedDestinations() {
        }
        
        public mostVistedDestinations(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mostVistedDestinationsResponse", WrapperNamespace="http://armandorv.com/easytravel/travelsws", IsWrapped=true)]
    internal partial class mostVistedDestinationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://armandorv.com/easytravel/travelsws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public destiny[] @return;
        
        public mostVistedDestinationsResponse() {
        }
        
        public mostVistedDestinationsResponse(destiny[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="isVisited", WrapperNamespace="http://armandorv.com/easytravel/travelsws", IsWrapped=true)]
    internal partial class isVisited {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://armandorv.com/easytravel/travelsws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://armandorv.com/easytravel/travelsws", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string destinyName;
        
        public isVisited() {
        }
        
        public isVisited(string username, string destinyName) {
            this.username = username;
            this.destinyName = destinyName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="isVisitedResponse", WrapperNamespace="http://armandorv.com/easytravel/travelsws", IsWrapped=true)]
    internal partial class isVisitedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://armandorv.com/easytravel/travelsws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public isVisitedResponse() {
        }
        
        public isVisitedResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="numberTravelsByDestination", WrapperNamespace="http://armandorv.com/easytravel/travelsws", IsWrapped=true)]
    internal partial class numberTravelsByDestination {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://armandorv.com/easytravel/travelsws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string destinyName;
        
        public numberTravelsByDestination() {
        }
        
        public numberTravelsByDestination(string destinyName) {
            this.destinyName = destinyName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="numberTravelsByDestinationResponse", WrapperNamespace="http://armandorv.com/easytravel/travelsws", IsWrapped=true)]
    internal partial class numberTravelsByDestinationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://armandorv.com/easytravel/travelsws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public numberTravelsByDestinationResponse() {
        }
        
        public numberTravelsByDestinationResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface travelsWebServiceChannel : Armandorv.EasytravelWsClient.TravelsWs.travelsWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class travelsWebServiceClient : System.ServiceModel.ClientBase<Armandorv.EasytravelWsClient.TravelsWs.travelsWebService>, Armandorv.EasytravelWsClient.TravelsWs.travelsWebService {
        
        public travelsWebServiceClient() {
        }
        
        public travelsWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public travelsWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public travelsWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public travelsWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Armandorv.EasytravelWsClient.TravelsWs.mostVistedDestinationResponse Armandorv.EasytravelWsClient.TravelsWs.travelsWebService.mostVistedDestination(Armandorv.EasytravelWsClient.TravelsWs.mostVistedDestination request) {
            return base.Channel.mostVistedDestination(request);
        }
        
        public Armandorv.EasytravelWsClient.TravelsWs.destiny mostVistedDestination() {
            Armandorv.EasytravelWsClient.TravelsWs.mostVistedDestination inValue = new Armandorv.EasytravelWsClient.TravelsWs.mostVistedDestination();
            Armandorv.EasytravelWsClient.TravelsWs.mostVistedDestinationResponse retVal = ((Armandorv.EasytravelWsClient.TravelsWs.travelsWebService)(this)).mostVistedDestination(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Armandorv.EasytravelWsClient.TravelsWs.getTravelsResponse Armandorv.EasytravelWsClient.TravelsWs.travelsWebService.getTravels(Armandorv.EasytravelWsClient.TravelsWs.getTravels request) {
            return base.Channel.getTravels(request);
        }
        
        public travel[] getTravels(string term) {
            Armandorv.EasytravelWsClient.TravelsWs.getTravels inValue = new Armandorv.EasytravelWsClient.TravelsWs.getTravels();
            inValue.term = term;
            Armandorv.EasytravelWsClient.TravelsWs.getTravelsResponse retVal = ((Armandorv.EasytravelWsClient.TravelsWs.travelsWebService)(this)).getTravels(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Armandorv.EasytravelWsClient.TravelsWs.mostVistedDestinationsResponse Armandorv.EasytravelWsClient.TravelsWs.travelsWebService.mostVistedDestinations(Armandorv.EasytravelWsClient.TravelsWs.mostVistedDestinations request) {
            return base.Channel.mostVistedDestinations(request);
        }
        
        public destiny[] mostVistedDestinations(int arg0) {
            Armandorv.EasytravelWsClient.TravelsWs.mostVistedDestinations inValue = new Armandorv.EasytravelWsClient.TravelsWs.mostVistedDestinations();
            inValue.arg0 = arg0;
            Armandorv.EasytravelWsClient.TravelsWs.mostVistedDestinationsResponse retVal = ((Armandorv.EasytravelWsClient.TravelsWs.travelsWebService)(this)).mostVistedDestinations(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Armandorv.EasytravelWsClient.TravelsWs.isVisitedResponse Armandorv.EasytravelWsClient.TravelsWs.travelsWebService.isVisited(Armandorv.EasytravelWsClient.TravelsWs.isVisited request) {
            return base.Channel.isVisited(request);
        }
        
        public bool isVisited(string username, string destinyName) {
            Armandorv.EasytravelWsClient.TravelsWs.isVisited inValue = new Armandorv.EasytravelWsClient.TravelsWs.isVisited();
            inValue.username = username;
            inValue.destinyName = destinyName;
            Armandorv.EasytravelWsClient.TravelsWs.isVisitedResponse retVal = ((Armandorv.EasytravelWsClient.TravelsWs.travelsWebService)(this)).isVisited(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Armandorv.EasytravelWsClient.TravelsWs.numberTravelsByDestinationResponse Armandorv.EasytravelWsClient.TravelsWs.travelsWebService.numberTravelsByDestination(Armandorv.EasytravelWsClient.TravelsWs.numberTravelsByDestination request) {
            return base.Channel.numberTravelsByDestination(request);
        }
        
        public int numberTravelsByDestination(string destinyName) {
            Armandorv.EasytravelWsClient.TravelsWs.numberTravelsByDestination inValue = new Armandorv.EasytravelWsClient.TravelsWs.numberTravelsByDestination();
            inValue.destinyName = destinyName;
            Armandorv.EasytravelWsClient.TravelsWs.numberTravelsByDestinationResponse retVal = ((Armandorv.EasytravelWsClient.TravelsWs.travelsWebService)(this)).numberTravelsByDestination(inValue);
            return retVal.@return;
        }
    }
}
